[package]
name = "at_tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.22.2"
webpki-roots = "0.26.1"
log = "0.4.20"
