name: Clippy
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install Rust
        run: rustup update stable

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy
