name: Clippy
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install Rust
        run: rustup update stable

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy
